// domain/errors/errorCodeToStatus.ts
import { DomainErrorCode } from "./DomainError";

export const ERROR_CODE_TO_STATUS: Record<DomainErrorCode, number> = {
  SOLICITUD_SIN_PRODUCTOS: 422,
  CANTIDAD_PRODUCTO_INVALIDA: 422,
  ESTADO_NO_CANCELABLE: 409,
  ESTADO_NO_ANULABLE: 409,
  TRANSICION_INVALIDA: 409,
  SOLICITUD_NO_ENCONTRADA: 404,
  REMITENTE_NO_ENCONTRADO: 404,
  PRODUCTO_NO_ENCONTRADO: 404,
  PERMISO_DENEGADO: 403,
  ROL_INVALIDO: 403,
  CUENTA_NO_APROBADA: 403,
  FALTA_ID_BASE: 422,
  REMITENTE_NO_SELECCIONADO: 422,
  STOCK_INSUFICIENTE: 409,
};
